server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zl
    username: ceelia
    password: kb1cad
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        # format_sql: true
        # ddl-auto: update

  security:
    user:
      name: celiae
      password: hjkl;
